#!/usr/bin/env bash
# env-detect.sh - discover the LocalWP/Mac toolchain once per session and write export
# lines to a file you can `source`. Fixes two recurring time-sinks:
#   1. PATH thrashing ("command not found" for curl/node/sort) - sets a safe PATH.
#   2. The multi-site socket trap: `ls run/*/mysql/mysqld.sock | head -1` is NON-deterministic
#      when >1 LocalWP site runs and silently picks the WRONG site's DB. This matches the
#      socket to the site by querying each DB's siteurl.
#
# Usage:
#   bash env-detect.sh                       # detect bins; if 1 socket use it, else list them
#   bash env-detect.sh --url localhost:PORT # pick the socket whose siteurl matches
#   source ~/.cache/fig2wp/env.sh            # then use $UZ_SOCK $PHP $MYSQL $MYSQLDUMP $CHS $NODE
export PATH=/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin:/opt/homebrew/bin
URL_HINT=""; [ "$1" = "--url" ] && URL_HINT="$2"
OUT="${FIG2WP_ENV:-$HOME/.cache/fig2wp/env.sh}"; mkdir -p "$(dirname "$OUT")"
LS="/Applications/Local.app/Contents/Resources/extraResources/lightning-services"
newest(){ ls -d $1 2>/dev/null | sort -V | tail -1; }

PHP=$(newest "$LS/php-*/bin/darwin*/bin/php")
MYSQL=$(newest "$LS/mysql-*/bin/darwin*/bin/mysql")
MYSQLDUMP=$(newest "$LS/mysql-*/bin/darwin*/bin/mysqldump")
CHS=$(newest "$HOME/Library/Caches/ms-playwright/chromium_headless_shell-*/chrome-headless-shell-mac-*/chrome-headless-shell")
NODE=$(command -v node || newest "$HOME/.nvm/versions/node/*/bin/node")
FIGMA_PAT="${FIGMA_PAT:-$(zsh -c 'source ~/.zshrc 2>/dev/null; echo $FIGMA_PAT' 2>/dev/null)}"

# --- resolve the right MySQL socket ---
SOCK=""; declare -a SOCKS=()
while IFS= read -r s; do [ -n "$s" ] && SOCKS+=("$s"); done < <(ls "$HOME/Library/Application Support/Local/run/"*/mysql/mysqld.sock 2>/dev/null)
echo "found ${#SOCKS[@]} running LocalWP socket(s):"
for s in "${SOCKS[@]}"; do
  url=$("$MYSQL" --socket="$s" -uroot -proot -N -e "SELECT option_value FROM local.wp_options WHERE option_name='siteurl' LIMIT 1" 2>/dev/null)
  echo "  $url   <-  $s"
  if [ -n "$URL_HINT" ] && [[ "$url" == *"$URL_HINT"* ]]; then SOCK="$s"; fi
done
if [ -z "$SOCK" ]; then
  if [ "${#SOCKS[@]}" -eq 1 ]; then SOCK="${SOCKS[0]}";
  elif [ -n "$URL_HINT" ]; then echo "!! no socket matched '$URL_HINT'";
  else echo "!! multiple sockets - re-run with --url localhost:PORT to pick the right one (avoids the wrong-DB trap)"; fi
fi

{
  echo "# generated by env-detect.sh - source me"
  echo "export PATH=/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin:/opt/homebrew/bin"
  echo "export PHP='$PHP'"
  echo "export MYSQL='$MYSQL'"
  echo "export MYSQLDUMP='$MYSQLDUMP'"
  echo "export CHS='$CHS'"
  echo "export NODE='$NODE'"
  echo "export UZ_SOCK='$SOCK'"
  [ -n "$FIGMA_PAT" ] && echo "export FIGMA_PAT='$FIGMA_PAT'"
} > "$OUT"
chmod 600 "$OUT" 2>/dev/null   # contains FIGMA_PAT - keep it user-only
echo "--- wrote $OUT (chmod 600) ---"
sed -e "s#$HOME#~#g" -e "s#\(FIGMA_PAT='figd_\).*#\1***masked***#" "$OUT"
[ -z "$SOCK" ] && exit 1 || exit 0
